const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
async function api(path){const r=await fetch(path,{credentials:'same-origin'});let j={};try{j=await r.json()}catch{j={detail:await r.text()}}if(!r.ok)throw Error(j.detail||r.statusText);return j}
function show(id,value){$(id).textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
function rows(items,render){return items.length?items.map(render).join(''):'No records.'}
async function loadSummary(){try{const s=await api('/api/reference/shark6/summary');$('#referenceState').textContent='REFERENCE READY';$('#referenceState').className='badge ok';$('#referenceSummary').innerHTML=`<b>${esc(s.vehicle)}</b> · ${esc(s.powertrain)}<br>${s.counts.connector_records} connector records · ${s.counts.connector_pin_records} pin records · ${s.counts.network_segments} CAN/network segments · ${s.counts.diagram_records} diagrams · ${s.counts.module_records} modules<br><small>Source: ${esc(s.source.document)} · ${esc(s.source.verification)}</small>`}catch(e){$('#referenceState').textContent='UNAVAILABLE';$('#referenceState').className='badge bad';show('#referenceSummary',e.message)}}
async function loadLists(){try{const [networks,modules,diagrams,harnesses,wires]=await Promise.all([api('/api/reference/shark6/networks'),api('/api/reference/shark6/modules'),api('/api/reference/shark6/diagrams'),api('/api/reference/shark6/harnesses'),api('/api/reference/shark6/wire-colors')]);$('#networkSelect').innerHTML='<option value="">Select network…</option>'+networks.networks.map(n=>`<option value="${esc(n.name)}">${esc(n.name.replaceAll('_',' '))}</option>`).join('');$('#moduleList').innerHTML=rows(modules.modules,x=>`<div><code>${esc(x.module_id)}</code> · ${esc(x.name)}</div>`);$('#diagramList').innerHTML=rows(diagrams.diagrams,x=>`<div><code>${esc(x.diagram_id)}</code> · ${esc(x.title)}</div>`);$('#harnessList').innerHTML=rows(harnesses.harnesses,x=>`<div><code>${esc(x.code)}</code> · ${esc(x.name)}</div>`);$('#wireList').innerHTML=rows(wires.wire_colors,x=>`<div><code>${esc(x.code)}</code> · ${esc(x.color)}</div>`)}catch(e){for(const id of ['#moduleList','#diagramList','#harnessList','#wireList'])show(id,e.message)}}
async function search(){const q=$('#referenceQuery').value.trim();if(!q){show('#referenceResults','Enter a search term.');return}try{const r=await api(`/api/reference/shark6/search?q=${encodeURIComponent(q)}&limit=100`);$('#referenceResults').innerHTML=rows(r.results,item=>`<div style="margin:.4rem 0"><b>${esc(item.kind.toUpperCase())}</b> <code>${esc(item.key)}</code> · ${esc(item.text)}</div>`)}catch(e){show('#referenceResults',e.message)}}
async function lookupConnector(){const id=$('#connectorId').value.trim();if(!id){show('#connectorResult','Enter a connector ID.');return}try{show('#connectorResult',await api(`/api/reference/shark6/connectors/${encodeURIComponent(id)}`))}catch(e){show('#connectorResult',e.message)}}
async function loadNetwork(){const name=$('#networkSelect').value;if(!name){show('#networkResult','Select a network.');return}try{show('#networkResult',await api(`/api/reference/shark6/networks/${encodeURIComponent(name)}`))}catch(e){show('#networkResult',e.message)}}
$('#referenceSearch').onclick=search;$('#referenceQuery').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#connectorLookup').onclick=lookupConnector;$('#connectorId').addEventListener('keydown',e=>{if(e.key==='Enter')lookupConnector()});$('#networkSelect').onchange=loadNetwork;
loadSummary();loadLists();
