from __future__ import annotations

from .research_context import FieldResearchStore, ResearchClaim, ResearchSource

ALL_TERRAIN_SOURCES = [
    {
        "source_id": "yt-VspbGyxMZyo",
        "kind": "community",
        "title": "Early Shark user perspective / pre-production context",
        "url": "https://www.youtube.com/watch?v=VspbGyxMZyo",
        "grade": "C",
        "published_date": "2024-12",
        "video_id": "VspbGyxMZyo",
        "claim_summary": "Indexed discussion emphasizes separating pre-production observations from production vehicle conclusions.",
    },
    {
        "source_id": "yt-XU5JnUxgfE4",
        "kind": "community",
        "title": "Normal urban ownership use",
        "url": "https://www.youtube.com/watch?v=XU5JnUxgfE4",
        "grade": "C",
        "published_date": "2025-01",
        "video_id": "XU5JnUxgfE4",
        "claim_summary": "Indexed discussion frames ordinary daily driving as an important Shark usage baseline.",
    },
    {
        "source_id": "yt-P1Ca6onpjPo",
        "kind": "community",
        "title": "Early traction-control field test",
        "url": "https://www.youtube.com/watch?v=P1Ca6onpjPo",
        "grade": "C",
        "published_date": "2025-02-01",
        "video_id": "P1Ca6onpjPo",
        "claim_summary": "Community indexing points to brake-based traction behaviour as a physical validation target.",
    },
    {
        "source_id": "yt-g08V2Hf7EM0",
        "kind": "independent",
        "title": "BYD Shark 6 in high ambient heat and sand",
        "url": "https://www.youtube.com/watch?v=g08V2Hf7EM0",
        "grade": "B",
        "published_date": "2025-02",
        "video_id": "g08V2Hf7EM0",
        "claim_summary": "Public coverage makes ambient temperature, sand mode, SOC and thermal context relevant to repeatable sand testing.",
    },
    {
        "source_id": "yt-dATBFZ3axyY",
        "kind": "creator",
        "title": "BYD Shark 6 Test in the Victoria High Country - Coming Soon",
        "url": "https://www.youtube.com/watch?v=dATBFZ3axyY",
        "grade": "A",
        "published_date": "2025-02-09",
        "video_id": "dATBFZ3axyY",
        "claim_summary": "Creator material establishes a multi-episode high-country field-testing program.",
    },
    {
        "source_id": "yt-m5qzHvBv1Qc",
        "kind": "community",
        "title": "Real-world towing approximately 1.5 t over mixed driving",
        "url": "https://www.youtube.com/watch?v=m5qzHvBv1Qc",
        "grade": "C",
        "published_date": "2025-02",
        "video_id": "m5qzHvBv1Qc",
        "claim_summary": "Community summaries identify towing energy, route, fuel and operating-mode context as useful measurement targets; quoted arithmetic is not promoted as fact.",
    },
    {
        "source_id": "yt-m-2GBqEkYpM",
        "kind": "creator",
        "title": "The All Terrain BYD SHARK 6 in Australia",
        "url": "https://www.youtube.com/watch?v=m-2GBqEkYpM",
        "grade": "A",
        "published_date": "2025-02-18",
        "video_id": "m-2GBqEkYpM",
        "claim_summary": "Creator ownership framing spans daily driving, camping, towing and off-road use cases.",
    },
    {
        "source_id": "yt-hm6bx70UT6w",
        "kind": "creator",
        "title": "Hill revisit / software-fix proof video",
        "url": "https://www.youtube.com/watch?v=hm6bx70UT6w",
        "grade": "A",
        "published_date": "2025-02-20",
        "video_id": "hm6bx70UT6w",
        "claim_summary": "Creator attributes changed hill behaviour to a software fix and shows software version 56.1.2.2411280.1 V1.0.0; target-vehicle A/B validation remains required.",
    },
    {
        "source_id": "yt-m_8MI_TROvY",
        "kind": "creator",
        "title": "BYD Shark 6 Offroad Modes while Towing 1.8T",
        "url": "https://www.youtube.com/watch?v=m_8MI_TROvY",
        "grade": "A",
        "published_date": "2025-02-23",
        "video_id": "m_8MI_TROvY",
        "claim_summary": "Primary creator material for towing and terrain-mode interaction; community interpretation of connector-dependent mode availability remains a hypothesis.",
    },
    {
        "source_id": "yt-snTpboghEZE",
        "kind": "community",
        "title": "High-country steep / rocky climb segment",
        "url": "https://www.youtube.com/watch?v=snTpboghEZE",
        "grade": "C",
        "published_date": "2025-03",
        "video_id": "snTpboghEZE",
        "claim_summary": "Indexed discussion makes incline, articulation, terrain mode, wheel-speed deltas and tyre setup important context variables.",
    },
    {
        "source_id": "yt-uetp2urd1lM",
        "kind": "community",
        "title": "Victorian High Country full-version run / Jorgenson Track",
        "url": "https://www.youtube.com/watch?v=uetp2urd1lM",
        "grade": "C",
        "published_date": "2025-03",
        "video_id": "uetp2urd1lM",
        "claim_summary": "Indexed discussion identifies driver-technique annotations as useful context for comparing obstacle attempts.",
    },
    {
        "source_id": "yt-6IhfvNog-y4",
        "kind": "creator",
        "title": "Off-Road REAL WORLD TEST - BYD SHARK PHEV 24/7",
        "url": "https://www.youtube.com/watch?v=6IhfvNog-y4",
        "grade": "A",
        "published_date": "2025-03-13",
        "video_id": "6IhfvNog-y4",
        "claim_summary": "Creator high-country episode identifies software version 56.1.2.2411280.1 V1.0.0, supporting firmware persistence in session context.",
    },
    {
        "source_id": "yt-WogPjcDcK_g",
        "kind": "creator",
        "title": "Shark 6 capabilities in the Victorian High Country?",
        "url": "https://www.youtube.com/watch?v=WogPjcDcK_g",
        "grade": "A",
        "published_date": "2025-03-18",
        "video_id": "WogPjcDcK_g",
        "claim_summary": "Creator material supports a repeatable high-country test protocol rather than a generic off-road score.",
    },
    {
        "source_id": "yt-jfpaOGCmlcg",
        "kind": "community",
        "title": "Response to production Shark hill retest",
        "url": "https://www.youtube.com/watch?v=jfpaOGCmlcg",
        "grade": "C",
        "published_date": "2025-04",
        "video_id": "jfpaOGCmlcg",
        "claim_summary": "Public debate distinguishes available power from traction delivered during articulation, motivating separate observation dimensions.",
    },
    {
        "source_id": "yt-CvNKh5U_guc",
        "kind": "community",
        "title": "Beer O'Clock hill attempt / damage lesson",
        "url": "https://www.youtube.com/watch?v=CvNKh5U_guc",
        "grade": "C",
        "published_date": "2025-04-07",
        "video_id": "CvNKh5U_guc",
        "claim_summary": "Community interpretation treats this attempt as a technique and incident-learning case, motivating run markers and post-run inspection evidence.",
    },
    {
        "source_id": "yt-h0FXa3pQ1Ok",
        "kind": "community",
        "title": "Hill climb technique comparison",
        "url": "https://www.youtube.com/watch?v=h0FXa3pQ1Ok",
        "grade": "C",
        "published_date": "2025-04",
        "video_id": "h0FXa3pQ1Ok",
        "claim_summary": "Indexed discussion highlights driver-technique differences; Vision should annotate actions rather than infer universal technique outcomes.",
    },
    {
        "source_id": "yt-D3GVrWj5bsg",
        "kind": "creator",
        "title": "All Terrain Action BYD Shark 6 Lives On!",
        "url": "https://www.youtube.com/watch?v=D3GVrWj5bsg",
        "grade": "A",
        "published_date": "2025-05-01",
        "video_id": "D3GVrWj5bsg",
        "claim_summary": "Creator vehicle-history material supports linking incident and repair history to later recordings.",
    },
    {
        "source_id": "yt-EP85qjV7joM",
        "kind": "community",
        "title": "Early modified-Shark coding / control R&D",
        "url": "https://www.youtube.com/watch?v=EP85qjV7joM",
        "grade": "C",
        "published_date": "2025-05-06",
        "video_id": "EP85qjV7joM",
        "claim_summary": "Community discussion references active low-speed control experiments; Vision uses this only to motivate passive response visualisation and does not implement vehicle control.",
    },
    {
        "source_id": "yt-End6ZU8GKdI",
        "kind": "community",
        "title": "Later off-road attempt after Beer O'Clock",
        "url": "https://www.youtube.com/watch?v=End6ZU8GKdI",
        "grade": "C",
        "published_date": "2025-05",
        "video_id": "End6ZU8GKdI",
        "claim_summary": "Community references motivate explicit ESC/TCS/mode context when comparing repeated obstacle attempts.",
    },
    {
        "source_id": "yt-THFdPtte59M",
        "kind": "community",
        "title": "Corrugation / brake warning field lesson",
        "url": "https://www.youtube.com/watch?v=THFdPtte59M",
        "grade": "C",
        "published_date": "2025-06-23",
        "video_id": "THFdPtte59M",
        "claim_summary": "Community report links a warning, rough-road use and later mechanical inspection; Vision treats it as an incident-timeline hypothesis, not a diagnosis.",
    },
    {
        "source_id": "yt-LzORFvTfIMo",
        "kind": "creator",
        "title": "We've Quietly Transformed the All Terrain Shark",
        "url": "https://www.youtube.com/watch?v=LzORFvTfIMo",
        "grade": "A",
        "published_date": "2025-08-07",
        "video_id": "LzORFvTfIMo",
        "claim_summary": "Creator modification milestone shows why stock and modified vehicle captures require explicit modification provenance.",
    },
    {
        "source_id": "yt-5RMPdJeU6k8",
        "kind": "creator",
        "title": "Software Modified BYD SHARK 6 OFFROAD (ALL TERRAIN EVX)",
        "url": "https://www.youtube.com/watch?v=5RMPdJeU6k8",
        "grade": "A",
        "published_date": "2025-12-20",
        "video_id": "5RMPdJeU6k8",
        "claim_summary": "EVX progress material is a useful stock-vs-modified observational comparison target; active EVX control is outside Vision's supported boundary.",
    },
    {
        "source_id": "yt-PxzFOrnmt0U",
        "kind": "creator",
        "title": "Testing All Terrain EVX in SHARK 6 Towing 37% to 70% in 13 mins",
        "url": "https://www.youtube.com/watch?v=PxzFOrnmt0U",
        "grade": "A",
        "published_date": "2026-01-04",
        "video_id": "PxzFOrnmt0U",
        "claim_summary": "Title reports a 37% to 70% SOC change in 13 minutes during an EVX towing test; Vision should capture underlying SOC, engine/generator, load and temperature context before generalising.",
    },
    {
        "source_id": "web-evx-roadmap",
        "kind": "vendor_product",
        "title": "All Terrain EVX roadmap",
        "url": "https://allterrainx.com.au/xmode",
        "grade": "A",
        "claim_summary": "Vendor roadmap describes staged R&D, pre-production, UI, release and later infotainment/mobile/OTA work; roadmap dates remain time-sensitive vendor statements.",
    },
    {
        "source_id": "web-evx-shop",
        "kind": "vendor_product",
        "title": "All Terrain EVX shop listing",
        "url": "https://shop.allterrain.com.au",
        "grade": "A",
        "claim_summary": "Vendor shop establishes the modification ecosystem and reinforces the need for a vehicle modification ledger.",
    },
    {
        "source_id": "web-shark-spec",
        "kind": "vendor_product",
        "title": "All Terrain BYD Shark 6 specification page",
        "url": "https://ev.allterrain.com.au/byd-shark-6-specs",
        "grade": "A",
        "claim_summary": "Vendor specification page is a dated fleet slice and must not be treated as an immutable cross-model-year schema.",
    },
]

ALL_TERRAIN_CLAIMS = [
    {
        "claim_id": "firmware-can-change-observed-terrain-behaviour",
        "statement": "Vehicle software revision may materially change observed terrain behaviour, so firmware must be recorded for every comparable run.",
        "domain": "firmware",
        "source_refs": ["yt-hm6bx70UT6w", "yt-6IhfvNog-y4"],
        "grade": "A",
        "confidence": 0.75,
        "validation_state": "needs_physical_validation",
        "required_evidence": ["same target vehicle", "matched route or obstacle", "firmware before/after", "same tyres and load where practical"],
    },
    {
        "claim_id": "trailer-state-may-change-mode-availability",
        "statement": "Trailer connection or detection may change terrain-mode availability on some Shark firmware/variant combinations.",
        "domain": "towing-interlock",
        "source_refs": ["yt-m_8MI_TROvY"],
        "grade": "A",
        "confidence": 0.55,
        "validation_state": "needs_physical_validation",
        "required_evidence": ["target vehicle observation", "connector state", "vehicle trailer-detection state", "firmware", "available-mode UI evidence"],
    },
    {
        "claim_id": "soc-recovery-needs-run-context",
        "statement": "Generator-assisted SOC recovery under towing or sustained load is operationally useful but must be interpreted with load, route, thermal and software context.",
        "domain": "energy",
        "source_refs": ["yt-PxzFOrnmt0U", "yt-m5qzHvBv1Qc"],
        "grade": "A",
        "confidence": 0.7,
        "validation_state": "needs_physical_validation",
        "required_evidence": ["SOC time series", "engine/generator state", "vehicle speed", "route grade", "trailer/load", "ambient and temperatures where validated"],
    },
    {
        "claim_id": "rough-road-warning-needs-incident-timeline",
        "statement": "Warnings observed during rough-road use should be captured with recording context and later inspection evidence rather than converted directly into a mechanical diagnosis.",
        "domain": "incident",
        "source_refs": ["yt-THFdPtte59M"],
        "grade": "C",
        "confidence": 0.45,
        "validation_state": "hypothesis",
        "required_evidence": ["natural target-vehicle event", "warning/DTC snapshot", "time-correlated recording", "service inspection evidence"],
    },
    {
        "claim_id": "modification-state-is-required-comparison-context",
        "statement": "Tyres, suspension, bars, electrical accessories and other modifications can invalidate direct run-to-run comparisons unless modification state is recorded.",
        "domain": "modification",
        "source_refs": ["yt-LzORFvTfIMo", "web-evx-shop"],
        "grade": "A",
        "confidence": 0.9,
        "validation_state": "partially_validated",
        "required_evidence": ["operator modification ledger", "before/after baseline where relevant"],
    },
]


def seed_all_terrain_research(store: FieldResearchStore) -> dict:
    source_results = []
    for item in ALL_TERRAIN_SOURCES:
        source_results.append(store.put_source(ResearchSource.model_validate(item)))
    claim_results = []
    for item in ALL_TERRAIN_CLAIMS:
        claim_results.append(store.put_claim(ResearchClaim.model_validate(item)))
    return {
        "sources": len(source_results),
        "claims": len(claim_results),
        "sources_stored": sum(result["status"] == "stored" for result in source_results),
        "claims_stored": sum(result["status"] == "stored" for result in claim_results),
        "idempotent": all(result["status"] == "present" for result in source_results + claim_results),
    }
